on: [push]

jobs:
  as3schema:
    name: Validate AS3 Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate AS3 Schema
        id: hello
        uses: focrensh/hello-world-docker-action@v0.9.0
        with:
          declaration: 'as3.json'